import express, { Application } from "express";
import cookieParser from "cookie-parser";
import cors from "cors";
import sessionConfig from "./config/sessions.config";
import { helmetConfig } from "./security/helmet";
import { errorHandlers } from "./middlewares/error-handlers.middleware.";
import { rateLimiter } from "./security/rate-limit";
import { corsOptions } from "./config/cors.config";
import authRouter from "./router/auth.router";
import usersRouter from "./router/users.router";
import articleRouter from "./router/articel.router";
import pageViewRouter from "./router/page-view.route";

export const web: Application = express();
const rateLimit = new rateLimiter(15 * 60 * 1000, 100);
web.set("trust proxy", 1);
web.use(express.json());
web.use(express.urlencoded({ extended: true }));
web.use(cookieParser());
web.use(sessionConfig);
web.use(helmetConfig);
web.use(cors(corsOptions));
web.use(rateLimit.getMiddleware());
web.use("/api/auth", authRouter);
web.use("/api/users", usersRouter);
web.use("/api/articels", articleRouter);
web.use("/api/page-view", pageViewRouter);
web.use(errorHandlers);
